spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.19.6:30242/test?useUnicode=true&characterEncoding=utf-8
    username: pd_test_dev
    password: VFR5rgdf

server:
  port: 7777

#初始化加载DispatcherServlet
spring.mvc.servlet.load-on-startup: 1

mybatis:
    type-aliases-package: com.conan.demo.model
    mapper-locations: classpath:mapper/*.xml
