spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    # mysql 5.x.x
    # driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    # username: root
    # password: 123
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2.max-idle: 10
    dbcp2.max-total: 50
    dbcp2.max-wait-millis: 10000
    dbcp2.initial-size: 5


  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    #初始化加载DispatcherServlet
    servlet:
      load-on-startup: 1


# http://192.168.1.2:7777/springboot/ 配置如下
server:
  port: 7777
  servlet:
    context-path: /springboot


mybatis:
    type-aliases-package: com.conan.demo.model
    mapper-locations: classpath:mapper/*.xml

# 打印mybatis的sql语句
logging:
  level:
    com.conan.demo.mapper: debug
    org.mybatis: DEBUG

